# Generated by Django 4.0.3 on 2022-03-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_alter_item_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='item',
            field=models.CharField(max_length=50),
        ),
    ]
