# Generated by Django 4.0.3 on 2022-03-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0004_alter_tarea_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
